variation_name: test_config

# h5_file_name: "../2M_uncompressed.hdf5""
h5_filename: '../../generate_data/to_hdf5/Uniform_pi+_0-100GeV_standalone_TVT_Split_MinE00.hdf5'

do_input_normalization: True

n_epochs: 50
batch_size: 1000
patience: 10
loss: 'mae' #mse
n_latent_dim: 128
dropout_rate: 0.1

learning_rate: 1e-3
learning_decay_rate: 0.5

shuffle_split: True #Turn FALSE for images!
train_shuffle: True #Turn TRUE for images!

train_split: 0.6
val_split: 0.25
test_split: 0.15

