data:
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_pi+_Uniform_0-140Gev_17deg_1/ # 200, 99, 100
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_pi+_100_10k_10-30deg_1/ # 108, 40, 50
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_pi+_uniform_2.83deg_100_6k_1/  
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_e-_Uniform_0-95GeV_17deg_1/
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_pi+_100_10k_17deg_ECAL_1/   # 80, 36, 36
  #data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_e-_150_10k_17deg_ECAL_updated_1/   ## 88 44   44
  data_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/log10_pi+_100_10k_10-30-deg_ECAL_updated_1/  ## 85 30 49
  particle_type: pion
  num_train_files: 85
  num_val_files: 30
  num_test_files: 49
  batch_size: 2048
  shuffle: False
  num_procs: 2
  preprocess: True
  output_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/DeepSets_output/Deepset_Models/ECAL_HCAL_range_angle/preprocessed_data_pp_3D
  already_preprocessed: False
  calc_stats: True
model:
  block_type: deepsets
  num_blocks: 1
  num_layers: 4
  latent_size: 64
  concat_input: True
  reducer: mean
  edge_block_opt:
    use_edges: True
    use_receiver_nodes: True
    use_sender_nodes: True
    use_globals: True
  node_block_opt:
    use_received_edges: True
    use_sent_edges: False
    use_nodes: True
    use_globals: True
  global_block_opt:
    use_edges: False
    use_nodes: True
    use_globals: True
training:
  epochs: 100
  num_features: 3
  output_dim: 2
  include_ecal: True
  hadronic_detector: hcal
  learning_rate: 1.e-3
  save_dir: /media/miguel/Elements/Data_hcali/Data1/log10_Uniform_03-23/DeepSets_output/Deepset_Models/ECAL_HCAL_range_angle/results_3D_size64_lre3_4Lay_pp_mse/
