data:
  already_preprocessed: False
  batch_size: 256
  calc_stats: True
  data_dir: /usr/workspace/hip/eic/log10_Uniform_03-23/ECCE_HCAL_Files/hcal_pi+_log10continuous_1GeV-150GeV_10deg-30deg_07-21-23/
  num_procs: 32
  num_train_files: 10
  num_val_files: 5
  num_test_files: 5
  output_dir: preprocessed_data/
  particle_type: pion
  preprocess: true
  shuffle: True
  num_features: 4
  k: 10
  hadronic_detector: hcal
  include_ecal: true
model:
  block_type: deepsets
  num_blocks: 1
  num_layers: 4
  latent_size: 64
  concat_input: True
  reducer: mean
training:
  epochs: 10
  learning_rate: 0.001
  save_dir: results/
